services:
  backend:
    build: ./backend
    container_name: action-kanban-backend
    ports:
      - "13000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./backend/data:/app/data
    networks:
      - kanban-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: action-kanban-frontend
    ports:
      - "15173:80"
    depends_on:
      - backend
    networks:
      - kanban-network

networks:
  kanban-network:
    driver: bridge
    name: action-kanban-network